@extends('layout.app')
@section('content')
<section class="blog-page" style="padding-top: 160px !important;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="blog-details news-slid">
                    <div class="news-text">
                        <div class="blog-hover">
                            <h4>Refund Policy</h4>
                        </div>
                        <p>
                            Thank you for choosing our astrology consultation services. We strive to provide accurate
                            and
                            insightful readings to enhance your understanding and guide you through various aspects of
                            your life. Please read our refund policy carefully.
                        </p>
                        <h5>Refund Policy:</h5>
                        <p>
                            Due to the nature of our astrology consultation services, we regret to inform you that no
                            refunds are applicable after the consultation has been provided.
                        </p>
                        <h5>Cancellation Policy:</h5>
                        <p>
                            If you need to cancel your scheduled consultation, we kindly ask for at least 24 hours'
                            notice prior to the scheduled time. In case of cancellation within this time frame, we will
                            make every effort to reschedule your appointment at a convenient time for both parties.
                        </p>
                        <h5>No-Show Policy:</h5>
                        <p>
                            If you fail to attend the scheduled consultation without prior notice, it will be considered
                            a no-show. In such cases, the consultation fee will be non-refundable.
                        </p>
                        <h5>Technical Issues:</h5>
                        <p>
                            In the rare event of technical issues preventing the completion of the consultation, we
                            will make every effort to resolve the problem promptly. If the issue persists, we may, at
                            our discretion, reschedule the consultation or provide a partial refund.
                        </p>
                        <h5>Contact Us:</h5>
                        <p>
                            If you encounter any issues or have questions about our refund policy, please contact our
                            customer support.
                        </p>
                        <p><strong>Note:</strong> This refund policy is effective as of [date] and may be subject to
                            change. Any modifications will be posted on our website, and you are encouraged to review
                            this policy periodically.</p>
                        <p>By engaging in our astrology consultation services, you acknowledge that you have read,
                            understood, and agree to abide by this refund policy. Thank you for your understanding.</p>
                    </div>
                    <div class="news-text">
                        <div class="blog-hover">
                            <h4>Changes to This Refund Policy</h4>
                        </div>
                        <p>
                            We may update our Refund Policy from time to time. Thus, you are advised to review this
                            page periodically for any changes. We will notify you of any changes by posting the new
                            Refund Policy on this page.
                        </p>
                        <p>
                            This refund policy is effective as of [date].
                        </p>
                    </div>
                    <div class="news-text">
                        <div class="blog-hover">
                            <h4>Contact Us</h4>
                        </div>
                        <p>
                            If you have any questions or suggestions about our Refund Policy, do not hesitate to
                            contact us at [your contact email].
                        </p>
                        <p>This Refund Policy page was generated by <a
                                href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank"
                                rel="noopener noreferrer">App Privacy Policy Generator</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection
